loop services until certificates exist

diff --git a/rootfs/etc/s6/services/20-postfix/run b/rootfs/etc/s6/services/20-postfix/run
--- a/rootfs/etc/s6/services/20-postfix/run
+++ b/rootfs/etc/s6/services/20-postfix/run
@@ -1,5 +1,11 @@
 #!/usr/bin/with-contenv sh
-sleep 2
+
+while [ ! -f /etc/postfix/virtual ] || [ ! -f /etc/postfix/virtual.db ]; do
+    test -f /etc/postfix/virtual || ( /bin/echo "[WARN  ] /etc/postfix/virtual not found" )
+    test -f /etc/postfix/virtual.db || ( /bin/echo "[WARN  ] /etc/postfix/virtual.db not found" )
+    echo "[INFO  ] postfix waiting for configuration initialization ..."
+    sleep 2
+done
 
 echo "[NOTICE] Starting postfix"
 exec /usr/sbin/postfix start-fg
diff --git a/rootfs/etc/s6/services/30-dovecot/run b/rootfs/etc/s6/services/30-dovecot/run
--- a/rootfs/etc/s6/services/30-dovecot/run
+++ b/rootfs/etc/s6/services/30-dovecot/run
@@ -1,4 +1,11 @@
 #!/usr/bin/with-contenv sh
 
+while [ ! -f /etc/ssl/certificate.pem ] || [ ! -f /etc/ssl/key.pem ]; do
+    test -f /etc/ssl/certificate.pem || ( /bin/echo "[WARN  ] /etc/ssl/certificate.pem not found" )
+    test -f /etc/ssl/key.pem || ( /bin/echo "[WARN  ] /etc/ssl/key.pem not found" )
+    echo "[INFO  ] dovecot waiting for certificates..."
+    sleep 2
+done
+
 echo "[NOTICE] Starting dovecot"
 exec /usr/sbin/dovecot -F
