begin s6-overlay v3 restructure

diff --git a/rootfs/etc/s6-overlay/s6-rc.d/postfix/run b/rootfs/etc/s6-overlay/s6-rc.d/postfix/run
--- a/rootfs/etc/s6-overlay/s6-rc.d/postfix/run
+++ b/rootfs/etc/s6-overlay/s6-rc.d/postfix/run
@@ -1,8 +1,10 @@
-#!/usr/bin/with-contenv sh
+#!/command/with-contenv sh
 
-while [ ! -f /etc/postfix/virtual ] || [ ! -f /etc/postfix/virtual.db ]; do
+chown catchall:catchall /var/mail
+
+while [ ! -f /etc/postfix/virtual ] || [ ! -f /etc/postfix/virtual.lmdb ]; do
     test -f /etc/postfix/virtual || ( /bin/echo "[WARN  ] /etc/postfix/virtual not found" )
-    test -f /etc/postfix/virtual.db || ( /bin/echo "[WARN  ] /etc/postfix/virtual.db not found" )
+    test -f /etc/postfix/virtual.lmdb || ( /bin/echo "[WARN  ] /etc/postfix/virtual.lmdb not found" )
     echo "[INFO  ] postfix waiting for configuration initialization ..."
     sleep 2
 done
