refactor: ubuntu 24.04

diff --git a/rootfs/etc/s6-overlay/s6-rc.d/postfix/run b/rootfs/etc/s6-overlay/s6-rc.d/postfix/run
--- a/rootfs/etc/s6-overlay/s6-rc.d/postfix/run
+++ b/rootfs/etc/s6-overlay/s6-rc.d/postfix/run
@@ -2,12 +2,16 @@
 
 chown catchall:catchall /var/mail
 
-while [ ! -f /etc/postfix/virtual ] || [ ! -f /etc/postfix/virtual.lmdb ]; do
+while [ ! -f /etc/postfix/virtual ] || [ ! -f /etc/postfix/virtual.db ]; do
     test -f /etc/postfix/virtual || ( /bin/echo "[WARN  ] /etc/postfix/virtual not found" )
-    test -f /etc/postfix/virtual.lmdb || ( /bin/echo "[WARN  ] /etc/postfix/virtual.lmdb not found" )
+    test -f /etc/postfix/virtual.db || ( /bin/echo "[WARN  ] /etc/postfix/virtual.db not found" )
     echo "[INFO  ] postfix waiting for configuration initialization ..."
     sleep 2
 done
+
+install -Dm644 /etc/resolv.conf /var/spool/postfix/etc/resolv.conf
+install -Dm644 /etc/hosts       /var/spool/postfix/etc/hosts
+install -Dm644 /etc/nsswitch.conf /var/spool/postfix/etc/nsswitch.conf
 
 echo "[NOTICE] Starting postfix"
 exec /usr/sbin/postfix start-fg
